/*
Navicat MySQL Data Transfer

Source Server         : MySqlConnection
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : ecocircuits

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2023-05-31 15:45:41
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `producteurs`
-- ----------------------------
DROP TABLE IF EXISTS `producteurs`;
CREATE TABLE `producteurs` (
  `id_producteur` bigint(20) NOT NULL AUTO_INCREMENT,
  `libelle` varchar(255) DEFAULT '',
  `adresse_postale` varchar(255) DEFAULT '',
  `description` varchar(1000) DEFAULT '',
  `tags` varchar(255) DEFAULT '',
  `mail` varchar(255) DEFAULT '',
  `rayon_livraison` float DEFAULT NULL,
  `id` bigint(20) NOT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  PRIMARY KEY (`id_producteur`)
) ENGINE=MyISAM AUTO_INCREMENT=114 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ----------------------------
-- Records of producteurs
-- ----------------------------
INSERT INTO `producteurs` VALUES ('1', 'ADPEP 45 EA La Noue du Bois', '25 Bd Jean Jaures, 45000 ORLEANS', 'L’Entreprise Adaptée La Noue du Bois (ADPEP 45) est situé à Dampierre en Burly. Elle emploie des personnes ayant une « reconnaissance en qualité de travailleur handicapé » avec une orientation en milieu de travail. Cette entreprise œuvre sur plusieurs activités de travail, comme l’entretien des jardins et espaces verts, le maraichage, ou encore diverses prestations de services, … L’activité maraichage compte 6 salariés depuis sa création en 2010. Nous produisons une diversité de légumes de saison sur une surface d’un ha de plein champ et 0.5 ha d’abris froids.', 'Agriculture biologique\r\nProduits : Légume', '', null, '0', '47.9023', '1.89319');
INSERT INTO `producteurs` VALUES ('2', 'ALLAIRE Daniel SAS', 'Le Bourg, 45460 St Aignan des Gues', null, 'Agriculture biologique\r\nFamille : TRANS\r\nProduits : Légume', '', null, '0', '47.8424', '2.31963');
INSERT INTO `producteurs` VALUES ('3', 'AgroPaul', 'Chemin des Maisons Rouges, 41700 Le Controis-en-Sologne', 'Entreprise familiale de transformation de légumes biologiques en 4ème gamme', 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nProduits : Légume', '', null, '0', '47.4183', '1.44034');
INSERT INTO `producteurs` VALUES ('4', 'Anthémis', 'Route de Marcilly en Gault, 41200 MILLANCAY', null, null, '', null, '0', '47.4634', '1.8681');
INSERT INTO `producteurs` VALUES ('5', 'Arlesthis', 'Pulant, 41370 Marchenoir', null, null, '', null, '0', '47.834', '1.42024');
INSERT INTO `producteurs` VALUES ('6', 'Association Atouts et Perspectives', '33 Rue des Bourgetteries, 37390 METTRAY', 'Les 4 Saisons d\'Atouts constitue l\'établissement producteur de légumes biologiques géré par l\'Association Atouts et Perspectives à tout âge.\r\n Situé à Mettray Tours Nord, cette entité s\'inscrit dans l\'insertion par l\'activité économique au service de l\'employabilité des personnes en situation de fragilité. Ce chantier d\'insertion, ouvert en 2020, accueille femmes ou hommes dans le cadre d\'un projet d\'économie social et solidaire de proximité afin de faciliter leur insertion sociale et professionnelle. \r\n 38 légumes bio de saison, de proximité, de qualité sont récoltés à maturité sur une surface de 2 hectares dont 300 m² sous abris. Peu de manipulations et de stockage sont appliqués.', 'Agriculture biologique\r\nCertificat : AB\r\nProduits : Légume\r\nRécolte à maturité\r\nSite internet : http://atouts-et-perspectives.fr', '', null, '0', '47.4478', '0.658057');
INSERT INTO `producteurs` VALUES ('7', 'Association Le Relais', '12 Place de Juranville, 18000 Bourges', 'Association de solidarité agissant sur l\'hébergement, l\'accès aux droits et l\'insertion professionnelle en chantiers d\'insertion utilisant des activités comme la maraîchage biologique et la transformation de fruits et légumes comme support.', 'Agriculture biologique\r\nProduits : Fruit, Légume', '', null, '0', '47.0833', '2.38837');
INSERT INTO `producteurs` VALUES ('8', 'Aux Jardins du Soubeau', 'Le Soubeau, 18570 Morthomiers', 'Ferme maraîchère, production de fruits et légumes de saison sous serres et en plein champ sur 2ha.', 'Agriculture biologique\r\nProduits : Fruit, Légume', '', null, '0', '47.0269', '2.25942');
INSERT INTO `producteurs` VALUES ('9', 'Aux Légumes Célestes', '49 Rue du Grand Orme, 45150 Férolles', null, null, '', null, '0', '47.8283', '2.13718');
INSERT INTO `producteurs` VALUES ('10', 'BENOIST Alexandre', 'Route de Tigy, 45600 VIGLAIN', null, null, '', null, '0', '47.7296', '2.29922');
INSERT INTO `producteurs` VALUES ('11', 'BRESLU Antoine', '11 rue de la Colombe, 41160 MOISY', null, null, '', null, '0', '47.9078', '1.3373');
INSERT INTO `producteurs` VALUES ('12', 'Berry graines', 'Rifardeaux, 18350 Nérondes', null, 'Agriculture biologique\r\nCertificat : Ecpcert\r\nFamille : GROUP\r\nProduits : Céréale\r\nSite internet : http://berrygraines.com', '', null, '0', '46.9994', '2.78167');
INSERT INTO `producteurs` VALUES ('13', 'Bio Centre Loire', '28 Rte de Saint-Aignan, 41700 Le Controis-en-Sologne', 'Bio Centre Loire est une coopérative de producteurs 100% Bio qui met en marché les FEL bio issus des fermes adhérentes en région Centre Val de Loire. Créé en 2016 par 7 producteurs, BCL rassemble aujourd\'hui 36 fermes au profil diversifié. La gamme proposée est large (Plus de 35 familles pour plus de 100 références produits). En 2021, BCL a commercialisé 3 000 t de FEL pour un chiffre d\'affaires de 4,4 millions d\'euros. Nous sommes spécialisés sur l\'expédition en frais (marché de demi-gros/gros). Nos producteurs ont leur siège social et leurs sites de production en région Centre VDL. Ils sont 100% bio et engagés dans la certification Bio Cohérence (pas de travailleurs détachés, pas de serres chauffées, pas de CMS, ...). Le stockage et le conditionnement ont lieu sur les fermes. Notre leitmotiv : Développer une agriculture biologique exigeante en région Centre Val de Loire en construisant des filières durables, équitables et rémunératrices pour les producteurs.', 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : GROUP\r\nProduits : Fruit, Légume', '', null, '0', '47.4122', '1.42496');
INSERT INTO `producteurs` VALUES ('14', 'CHAMPDAVOINE Baptiste', null, null, null, '', null, '0', null, null);
INSERT INTO `producteurs` VALUES ('15', 'Domaine de St Gilles', '68 Route de Thenay, 41400 Pontlevoy', null, null, '', null, '0', '47.3899', '1.26451');
INSERT INTO `producteurs` VALUES ('16', 'EARL ARIBAUD', 'La Pharmacie, 45150 Férolles', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Légume', '', null, '0', '47.8379', '2.10751');
INSERT INTO `producteurs` VALUES ('17', 'EARL BAIGNOUX', 'Baignoux, 41500 Villexanton', null, null, '', null, '0', '47.7468', '1.44714');
INSERT INTO `producteurs` VALUES ('18', 'EARL Biotope', 'Villerussien, 41500 Maves', null, null, '', null, '0', '47.7258', '1.37458');
INSERT INTO `producteurs` VALUES ('19', 'EARL DAVEAU', 'Bardie, 41370 St Leonard en beauce', null, null, '', null, '0', '47.786', '1.35868');
INSERT INTO `producteurs` VALUES ('20', 'EARL Grésillon', '4 Rue des prés, 28310 GOMMERVILLE', null, null, '', null, '0', '48.3589', '1.96801');
INSERT INTO `producteurs` VALUES ('21', 'EARL Jean-Baptiste BOURDELOUP', '24 Hameau de Lutz, 28150 Éole-en-Beauce', 'Installé en 2008 sur la ferme familiale en production de céréales (blé tendre, tournesol, lentilles, luzernes) et légumes frais destinés à l\'industrie, je me suis converti en bio en 2018. J\'ai développé une nouvelle production de légumes secs pour la vente en circuits courts en 2020. Je propose désormais de la lentille verte BIO en conditionnement de 500g et 10kg. J\'envisage d\'élargir la gamme de légumes secs avec une production de haricots secs.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Céréale, Légume\r\nVolonté de produire en agriculture biologique de conservation des sols (limiter le labour et favoriser les couverts végétaux).', '', null, '0', '48.2357', '1.70999');
INSERT INTO `producteurs` VALUES ('22', 'EARL LA JONCHERE', '138 Route d’Ouvrouer, 45110 Sigloy', null, null, '', null, '0', '47.8369', '2.20778');
INSERT INTO `producteurs` VALUES ('23', 'EARL LEPAGE Vincent', '12 Rue de Chateaudun, 41240 Beauce la Romaine', null, null, '', null, '0', '47.9688', '1.53695');
INSERT INTO `producteurs` VALUES ('24', 'EARL Le Champ d\'Eau', '7 Hameau de Bazainville, 45480 GRENEVILLE en BEAUCE', null, null, '', null, '0', '48.1877', '2.0999');
INSERT INTO `producteurs` VALUES ('25', 'EARL Les Caves du Lochois', '16 Rue de Vautrompeau, 37600 Loches', null, null, '', null, '0', '47.1178', '0.997744');
INSERT INTO `producteurs` VALUES ('26', 'EARL Les Epis d\'Or', '6 Rue des Epis d’Or, 28800 Neuvy-en-Dunois', null, null, '', null, '0', '48.2066', '1.54035');
INSERT INTO `producteurs` VALUES ('27', 'EARL Nouvellon Agri Bio', '6 Chemin de Cour-sur-loire, 41500 Mulsans', null, null, '', null, '0', '47.6853', '1.38956');
INSERT INTO `producteurs` VALUES ('28', 'EARL Philippe JUMEAU', '2 rue Albert CAMUNEAU, 28200 Thiville', null, null, '', null, '0', '48.0252', '1.37545');
INSERT INTO `producteurs` VALUES ('29', 'EARL Pontijou', '3 Rue des Vouzoirs, 41500 Maves', null, null, '', null, '0', '47.7385', '1.33528');
INSERT INTO `producteurs` VALUES ('30', 'EARL S;Guerin', 'Occonville 17 rue du lion, 28700 Le Gué de Longroi', null, null, '', null, '0', '48.4844', '1.71544');
INSERT INTO `producteurs` VALUES ('31', 'EARL Serres Bio Val', '257 Rue des Serres, 45590 Saint-Cyr-en-Val', null, null, '', null, '0', '47.8534', '1.95904');
INSERT INTO `producteurs` VALUES ('32', 'EARL Vazelle', 'Vazelle, 41130 Billy', null, null, '', null, '0', '47.3405', '1.53814');
INSERT INTO `producteurs` VALUES ('33', 'EARL Zou la Galinette', '443 Rue du Parc Floral, 45590 Saint-Cyr-en-Val', null, null, '', null, '0', '47.8563', '1.94694');
INSERT INTO `producteurs` VALUES ('34', 'EARL de la Bourgognerie', '18 Rue Trianon, 45310 Patay', null, null, '', null, '0', '48.0475', '1.694');
INSERT INTO `producteurs` VALUES ('35', 'EARL de la Ferme des 4 Vents', '6 rue des 4 Vents, 41500 La Chapelle-Saint-Martin', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Huile, Céréale, Légume', '', null, '0', '47.7359', '1.41223');
INSERT INTO `producteurs` VALUES ('36', 'EARL de la Galinette', '10 Boisville, 41240 Beauce la Romaine', null, null, '', null, '0', '47.9782', '1.48808');
INSERT INTO `producteurs` VALUES ('37', 'EARL de la Varenne', '2 Rue du Vignoble, 45300 DADONVILLE', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Céréale', '', null, '0', '48.1518', '2.23997');
INSERT INTO `producteurs` VALUES ('38', 'EARL des Ruesses', 'Les Ruesses, 18380 Presly', null, 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nProduits : Produit carné, Porc', '', null, '0', '47.3651', '2.35907');
INSERT INTO `producteurs` VALUES ('39', 'EARL du Bois Galant', '32 Rue Florimond Robertet, 28800 Alluyes', null, null, '', null, '0', '48.2286', '1.36148');
INSERT INTO `producteurs` VALUES ('40', 'EARL du Montet', 'Le Montet, 18120 Méreau', null, null, '', null, '0', '47.1614', '2.06235');
INSERT INTO `producteurs` VALUES ('41', 'EARL du Tacre', '82 Petite Rue, 45160 Saint-Hilaire-Saint-Mesmin', null, null, '', null, '0', '47.8563', '1.81099');
INSERT INTO `producteurs` VALUES ('42', 'EARL la Renardière', '5 Faubourg du Parc, 45480 Outarville', null, null, '', null, '0', '48.2382', '2.05739');
INSERT INTO `producteurs` VALUES ('43', 'Entraide Berruyère', '261 Route de Saint-michel, 18000 Bourges', 'Association loi 1901 créée en 1984 gérant des ateliers d\'insertion dont la culture maraîchère en biodynamie et des actions sociales. Son objectif : Aider des personnes en grande difficulté.', 'Agriculture biologique\r\nProduits : Légume', '', null, '0', '47.1042', '2.42392');
INSERT INTO `producteurs` VALUES ('44', 'FONTAINE Jérôme', '13 Dommarville, 28800 Sancheville', null, null, '', null, '0', '48.1746', '1.55641');
INSERT INTO `producteurs` VALUES ('45', 'Ferme de Léonard', '6 Rue des Marronniers, 28220 CLOYES sur LOIR', null, null, '', null, '0', '48.0286', '1.25552');
INSERT INTO `producteurs` VALUES ('46', 'Ferme de l\'Aulnay', 'Route de Tigy, 45600 Viglain', null, null, '', null, '0', '47.7296', '2.29922');
INSERT INTO `producteurs` VALUES ('47', 'Ferme de la Motte', '52, rue du Château, 41370 Talcy', 'La Ferme de la Motte est une entreprise familiale (5 frères et cousins) située à Talcy entre Beauce et Châteaux. Producteur BIO depuis 1997, la ferme produit aujourd\'hui (avec l\'aide de ses producteurs partenaires) sur plus de 400 ha BIO en région Centre Val de Loire. Les produits phares sont : ail, oignon, échalote, pomme de terre et courge.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Légume', '', null, '0', '47.7677', '1.44085');
INSERT INTO `producteurs` VALUES ('48', 'Fromagerie MAURICE', 'Bourdel, 37160 NEUILLY LE BRIGNON', 'Nous fabriquons à la ferme des produits laitiers bio avec le lait récoltés dans un périmètre de 25 km alentour.', 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nProduits : Produit laitier de vache\r\nSite internet : http://www.fromageriemaurice.fr', '', null, '0', '46.9667', '0.777409');
INSERT INTO `producteurs` VALUES ('49', 'GABB 18', '2701 route d\'Orléans BP 10, 18230 Saint Doulchard', null, 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : GROUP', '', null, '0', '47.1283', '2.36773');
INSERT INTO `producteurs` VALUES ('50', 'GAEC Ferme de la Cour', '22 Rue Fernand Boulon Seillac, 41190 Valloire sur Cisse', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Légume', '', null, '0', '47.5456', '1.1551');
INSERT INTO `producteurs` VALUES ('51', 'GAEC Hofstede', 'Ferme de la Garenne, 18800 BAUGY', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Céréale, Légume', '', null, '0', '47.0745', '2.72038');
INSERT INTO `producteurs` VALUES ('52', 'GAEC St Paul', '73 Rue St Jacques, 37600 LOCHES', null, null, '', null, '0', '47.1376', '0.999616');
INSERT INTO `producteurs` VALUES ('53', 'GAEC Ste Marie', 'Domaine Ste Marie des Dués, 45570 Ouzouer sur Loire', null, 'Agriculture biologique\r\nProduits : Volaille, Oeuf, Viande bovine, Produit carné\r\nSite internet : http://fermebiosaintemarie.e-monsite.com/', '', null, '0', '47.7714', '2.47471');
INSERT INTO `producteurs` VALUES ('54', 'GAEC de la Georgerie', '301 chemin de la georgerie, 37360 Rouziers-de-Touraine', 'La Ferme de la Georgerie est composée d\'Audrey et Cyrille associés co-gérants et d\'un salarié à temps partiel.\r\n Nous cultivons des céréales en agriculture biologique sur 120 hectares et transformons nos céréales en farines et pâtes sur la ferme. Nous approvisionnons boulangeries, épiceries et particuliers.', 'Agriculture en conversion biologique\r\nProduits : Céréale', '', null, '0', '47.5128', '0.667058');
INSERT INTO `producteurs` VALUES ('55', 'GAEC du Chat Blanc', '3 rue de champ boulain, 41500 Maves', null, 'Agriculture biologique\r\nCertificat : FR-BIO-10\r\nVente à la ferme\r\nProduits : Céréale\r\nSite internet : https://fr-fr.facebook.com/fermeduchatblanc/', '', null, '0', '47.7427', '1.36537');
INSERT INTO `producteurs` VALUES ('56', 'GAEC du Mesnil', '11 Onville, 45480 GRENEVILLE en BEAUCE', null, null, '', null, '0', '48.2016', '2.11118');
INSERT INTO `producteurs` VALUES ('57', 'GAUTHIER Hugues', '5 bis grande rue, 41370 LORGES', null, null, '', null, '0', '47.823', '1.49904');
INSERT INTO `producteurs` VALUES ('58', 'GOUEFFON Alexandre', 'Les Champarts, 45170 NEUVILLE aux BOIS', null, null, '', null, '0', '48.0644', '2.04466');
INSERT INTO `producteurs` VALUES ('59', 'HUGUET Emilien', '15 Rue des Breluquettes, 41500 Séris', null, null, '', null, '0', '47.7587', '1.50313');
INSERT INTO `producteurs` VALUES ('60', 'HUGUET Florentin', '21 Chemin de Paris, 41500 Seris', null, null, '', null, '0', '47.7625', '1.50292');
INSERT INTO `producteurs` VALUES ('61', 'Histoire de fruits', '7 Rue des Avanries, 37130 La Chapelle-aux-Naux', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Fruit', '', null, '0', '47.3079', '0.418563');
INSERT INTO `producteurs` VALUES ('62', 'ISA Entraide', '9 bis Avenue du Général de Gaulle, 18700 Aubigny sur Nère', null, 'Agriculture biologique\r\nProduits : Légume\r\nSite internet : http://www.isagroupe.fr', '', null, '0', '47.4879', '2.43689');
INSERT INTO `producteurs` VALUES ('63', 'Jean-David LOCHON', '5 Place St Georges, 28300 JOUY', 'Exploitation agricole, producteur de blé dur Bio, transformation de notre Blé dur Bio en pâtes artisanales semi-complètes depuis 2016.', 'Agriculture biologique\r\nLabel : Bio Ecocert\r\nCertificat : Bio\r\nProduits : Céréale', '', null, '0', '48.5125', '1.5511');
INSERT INTO `producteurs` VALUES ('64', 'Julie BLESSON-MAHAIS', '1 Rue du Presbytère, 41190 SANTENAY', 'Fabrication de muesli issu de l\'agriculture biologique.', 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nProduits : Céréale', '', null, '0', '47.5662', '1.1167');
INSERT INTO `producteurs` VALUES ('65', 'L\'Abeille de Sologne', '14 Rue des Sautereaux, 41300 Theillay', 'Eleveur d\'abeilles par passion, je suis à la tête de 200 ruches et exploite plusieurs ruchers en Sologne et en Berry. Je ne vends que des miels de ma production. Je propose une gamme de 10 miels et autres produits de la ruche certifiées bio.', 'Agriculture biologique\r\nProduits : Miel\r\nSite internet : http://www.abeilledesologne.fr', '', null, '0', '47.3174', '2.03578');
INSERT INTO `producteurs` VALUES ('66', 'LEGRAND Emmanuel', '16 Juvrainville, 28200 Villampuy', null, null, '', null, '0', '48.0155', '1.50346');
INSERT INTO `producteurs` VALUES ('67', 'LEXTERIAT Loïc', 'Le Grand Vignol, 36110 Vineuil', null, null, '', null, '0', '46.9318', '1.67561');
INSERT INTO `producteurs` VALUES ('68', 'La Ferme de Doublainville', 'Doublainville, 41240 BEAUCE LA ROMAINE', 'Jeune producteur installé en agriculture biologique depuis 2022, je produits des patates douce et pommes de terre, céréales et légumineuses.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Céréale, Légume', '', null, '0', '47.9689', '1.47968');
INSERT INTO `producteurs` VALUES ('69', 'La Ferme de Léonard', '6 Rue des Marronniers, 28220 Cloyes les 3 rivières', 'Ferme bio depuis 2017, production de céréales diverses (sarrazin, chanvre, chia...) de légumineuses, et légumes pleins champs (potimarrons, butternuts et autres courges.\r\n Une petite production de courgettes et tomates.', 'Agriculture biologique\r\nProduits : Céréale, Légume', '', null, '0', '48.0286', '1.25552');
INSERT INTO `producteurs` VALUES ('70', 'La Ferme des Perrières', '165 Rue des Perrières, 45160 Saint-Hilaire-Saint-Mesmin', 'Arboriculteur maraîcher depuis 1964 sur une exploitation de 20 ha..', 'Agriculture biologique\r\nLabel : Bio cohérence\r\nCertificat : Bio\r\nProduits : Fruit, Légume', '', null, '0', '47.8572', '1.83063');
INSERT INTO `producteurs` VALUES ('71', 'La Ferme du Relais', 'Le Relais, 36180 PELLEVOISIN', 'A la Ferme du Relais, nous cultivons des céréales diversifiées dans le respect de l\'agriculture paysanne et biologique.\r\n Nous transformons nos récoltes sur place en farines écrasées sur meule de pierre, en pains pur levain cuits dans un four à bois et en huile pressés à froid.\r\n A la saison, nous produisons également des asperges vertes et blanches à têtes violettes que nous récoltons et trions à la main.\r\n Afin d\'entretenir la biodiversité, et les paysages de notre Boischaut, nous avons plantés des haies et des arbres en agroforesteries dans nos parcelles cultivées.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Huile, Céréale', '', null, '0', '46.9849', '1.40966');
INSERT INTO `producteurs` VALUES ('72', 'La Gauloise Dorée', 'La Folie Le quartier, 37160 La Celle Saint Avant', null, 'Agriculture biologique\r\nProduits : Volaille', '', null, '0', '47.0392', '0.630076');
INSERT INTO `producteurs` VALUES ('73', 'La branche à fruits', 'La Toucherie, 37320 SAINT BRANCHS', null, 'Agriculture biologique\r\nLabel : Bio cohérence\r\nVente à la ferme\r\nProduits : Fruit', '', null, '0', '47.2542', '0.7308');
INSERT INTO `producteurs` VALUES ('74', 'Laiterie de Verneuil', 'Les Arcis, 37600 Verneuil sur Indre', 'Coopérative Touraine Berry, fabrication de beurre, lait et fromage de chèvre.', 'Agriculture biologique\r\nProduits : Produit laitier de chèvre, Produit laitier de vache\r\nSite internet : http://www.laiterie-de-verneuil.com', '', null, '0', '47.0702', '1.0518');
INSERT INTO `producteurs` VALUES ('75', 'Le Grain Libre', '5 route du Coudray, 37600 Saint jean Saint Germain', 'Le Grain Libre, c\'est un collectif de sept fermes bio du Sud Touraine unies par une envie forte de vivre une aventure commune : apprendre à valoriser nos céréales et à les transformer ensemble.\r\n C\'est dans l\'atelier de Saint-Jean-Saint-Germain que les grains de blé tendre de variétés paysannes passent entre les meules de granite du moulin pour devenir des farines.\r\n Simplement mélangées à un peu d\'eau, c\'est l\'extrudeuse qui donne forme à nos spécialités céréalières, type pâtes sèches.', 'Agriculture biologique\r\nN° Siret :80982627400015 N° TVA intracom. :FR53809826274\r\nProduits : Céréale', '', null, '0', '47.0815', '1.03412');
INSERT INTO `producteurs` VALUES ('76', 'Le goût des saisons', '2013 Route des Forêts, 18110 Saint-Martin-d\'Auxigny', 'Paysan maraîcher en agriculture biologique diversifiée. Je cultive sur la commune de St Martin d\'Auxigny et dans les marais de Bourges. Les cultures sont en places permanentes en agroécologie et un système verger - maraicher.', 'Agriculture biologique\r\nCertificat : Ecocert\r\nProduits : Fruit, Légume', '', null, '0', '47.2137', '2.38165');
INSERT INTO `producteurs` VALUES ('77', 'Le jardin du Breuil', '31 Le Breuil aux Gittons, 36700 CLION', 'Maraicher en agriculture biologique installé depuis juillet 2017 à Clion', 'Agriculture biologique\r\nCertificat : AB\r\nProduits : Légume', '', null, '0', '46.9627', '1.18103');
INSERT INTO `producteurs` VALUES ('78', 'Les Vergers du Closeau', '748 Route de Villesavin, 41250 Mont Près Chambord', 'Nous produisons des fruits à pépins (Pommes principalement et poires) ainsi que des fraises. Une diversification est engagée sur d\'autres petits fruits (framboises notamment). L\'ensemble de l\'exploitation est conduite en respectant le cahier des charges de l\'agriculture biologique. Le verger est encore en conversion tandis que le reste de l\'exploitation est labelisé AB.', 'Agriculture en conversion biologique\r\nProduits : Fruit, Boisson\r\nSite internet : http://www.lesvergersducloseau.fr', '', null, '0', '47.5424', '1.45438');
INSERT INTO `producteurs` VALUES ('79', 'Les jardins de Cocagnes', '112 Rue de Bas-rivière, 41000 Blois', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Fruit, Légume\r\nSite internet : http://www.association-biosolidaire.fr', '', null, '0', '47.5671', '1.32048');
INSERT INTO `producteurs` VALUES ('80', 'Les jardins de contrat', 'Roucheux, 37530 Montreuil-en-Touraine', null, 'Agriculture biologique\r\nProduits : Fruit, Légume', '', null, '0', '47.4928', '0.923041');
INSERT INTO `producteurs` VALUES ('81', 'Louis CAILLEAU', '66 Rue de la Motte, 45150 Darvoy', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Fruit, Légume', '', null, '0', '47.8563', '2.07225');
INSERT INTO `producteurs` VALUES ('82', 'Loïc COSSET', '16 bis Bel Air, 36500 CHEZELLES', 'Maraîcher bio depuis 2014, je produis des fruits et légumes traditionnels. J\'ai également choisi de me diversifier en produisant du raisin de table.\r\n Je cultive une surface de 8ha de légumes et 2ha20 de raisin de table.', 'Agriculture biologique\r\nProduits : Fruit, Légume', '', null, '0', '46.8851', '1.57285');
INSERT INTO `producteurs` VALUES ('83', 'MINEC-DUBE Jérôme', '555 Route de Saint-Jean de Braye, 45400 Semoy', 'Installé depuis 2014 sur une petite surface de 1.5 ha en production de légumes et fruits bio.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Fruit, Légume', '', null, '0', '47.9303', '1.95676');
INSERT INTO `producteurs` VALUES ('84', 'MORINEAU Xavier', 'Villeramard, 41500 Maves', null, null, '', null, '0', '47.7306', '1.38618');
INSERT INTO `producteurs` VALUES ('85', 'Négo Beauce', '5 La Frileuse, 28140 Orgères-en-Beauce', null, null, '', null, '0', '48.1364', '1.67489');
INSERT INTO `producteurs` VALUES ('86', 'POTHIER Sylvain', 'Hameau de Loupille, 28140 Péronville', null, null, '', null, '0', '48.0456', '1.5904');
INSERT INTO `producteurs` VALUES ('87', 'Porcs Bio du Centre', 'Gorgeat, 41100 Azé', 'Créée en 2008 la SARL «PORCS BIO DU CENTRE» comprend un groupe d’éleveurs de porcs, des charcutiers dont un titulaire du titre de « Maître Artisan ». Cette réunion témoigne de l’attachement et de l’engagement ancien des associés dans des valeurs d’authenticité\r\n très fortes des points de vue humain, environnemental et économique.\r\n Les fermes, conduites en polyculture-élevage 100 % bio couvrent la totalité des besoins alimentaires en céréales et en fourrage des porcs.\r\n Les porcs sont conduits par chaque éleveur à un abattoir local de petite taille où l’on prend en compte au maximum le bien-être animal.\r\n Les charcutiers expérimentent et mettent au point des recettes, utilisant au maximum les qualités des viandes des porcs fournis par les éleveurs.\r\n Ensemble ils coordonnent leurs savoirs faire et associent leurs compétences individuelles pour fournir ce qui leur semble être le meilleur des productions de terroir : pâté de campagne, Jambon de Vendée IGP, etc.\r\n L’essentiel des producti', 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nProduits : Agneau, Viande bovine, Produit carné, Porc', '', null, '0', '47.8416', '1.0125');
INSERT INTO `producteurs` VALUES ('88', 'Provinces Bio - Relais Vert', '71 Boulevard Alfred Nobel, 44400 Rezé', null, null, '', null, '0', '47.1594', '-1.55337');
INSERT INTO `producteurs` VALUES ('89', 'SAMYN Frédéric', '8 Les Tresseaux, 41330 Averdon', null, null, '', null, '0', '47.7006', '1.29764');
INSERT INTO `producteurs` VALUES ('90', 'SARL FFBIO', 'Lieu dit Chatenay, 28140 Bazoches en Dunois', null, null, '', null, '0', '48.102', '1.58956');
INSERT INTO `producteurs` VALUES ('91', 'SARL La Porte Dorée', '32 Route de Fougères, 41700 CHEVERNY', 'Transformation de fruits et légumes bio depuis 2011 à nos marques (Conserverie de Cheverny, Confiturerie de Cheverny, Confibio) et pour le compte de maraîchers et arboriculteurs locaux.', 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nProduits : Fruit, Confiture', '', null, '0', '47.4829', '1.42535');
INSERT INTO `producteurs` VALUES ('92', 'SARL Saute Mouton', 'Forcelles, 45510 TIGY', 'Exploitation familiale en polyculture-élevage 100% bio depuis 1996, sous label bio cohérence, avec une activité d\'accueil pédagogique à destination de tous les publics.', 'Agriculture biologique\r\nLabel : Bio cohérence\r\nProduits : Légume\r\nSite internet : http://www.saute-mouton.net', '', null, '0', '47.8168', '2.16264');
INSERT INTO `producteurs` VALUES ('93', 'SAS Brasserie Sancerroise', '258 Route d\'Amigny, 18300 Sancerre', 'A la recherche d\'une bière artisanale à Sancerre ?\r\n Nos bières sont toutes brassées localement dans le Centre de la France à Sancerre, selon d\'anciennes recettes, toutes différentes les unes des autres, ainsi nous vous donnons le choix entre : \r\n Infusion et décoction, fermentation haute et basse, bières filtrées ou non filtrées, bières refermentées en bouteilles ou non.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Boisson', '', null, '0', '47.3295', '2.82986');
INSERT INTO `producteurs` VALUES ('94', 'SAS Domaine du Coudray', 'Le Coudray, 18290 Civray', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Céréale', '', null, '0', '46.9842', '2.20276');
INSERT INTO `producteurs` VALUES ('95', 'SASU Ju\'Nature', '10 Rue du Petit Bois Ferme de la Paternelle, 37390 METTRAY', 'Céréalier Bio sur 184ha sur la commune de Mettray avec une activité de transformation à la ferme (huiles, lentilles, plats préparés) et une activité de compostage.', 'Agriculture biologique\r\nCertificat : Bio\r\nVente à la ferme\r\nProduits : Huile, Céréale\r\nSite internet : https://www.leschampsdejulien.com/', '', null, '0', '47.447', '0.658183');
INSERT INTO `producteurs` VALUES ('96', 'SCEA Ferme des Montmartins', 'D 72 Les Montmartins, 41350 SAINT CLAUDE DE DIRAY', null, null, '', null, '0', '47.6059', '1.42033');
INSERT INTO `producteurs` VALUES ('97', 'SCEA L\'Orée de la Brenne', 'Maisons Sinaud, 36700 Arpheuilles', null, null, '', null, '0', '46.915', '1.25191');
INSERT INTO `producteurs` VALUES ('98', 'SCEA La Croix des Vignes', '27 Rue de Beaugency, 41290 Oucques La Nouvelle', null, null, '', null, '0', '47.8229', '1.29961');
INSERT INTO `producteurs` VALUES ('99', 'SCEA La Tibiodaire', '4 Le Parc de la Thibaudiere, 37120 Courcoué', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Huile, Céréale', '', null, '0', '47.0156', '0.385549');
INSERT INTO `producteurs` VALUES ('100', 'SCEA Le Petit Bergeresse', 'Le Petit de Bergeresse, 45510 VIENNE en VAL', null, null, '', null, '0', '47.8096', '2.14777');
INSERT INTO `producteurs` VALUES ('101', 'SCEA Les Fourmis Vertes', '7 Rue de la Vacquerie, 41000 Blois', null, null, '', null, '0', '47.5723', '1.33773');
INSERT INTO `producteurs` VALUES ('102', 'SCEA Les Vergers', 'Petit Biche, 41370 Saint-Léonard-en-Beauce', null, null, '', null, '0', '47.8085', '1.38632');
INSERT INTO `producteurs` VALUES ('103', 'SCEA Obi', '14 Rue du Bout Hallé, 41500 Séris', null, null, '', null, '0', '47.7562', '1.50075');
INSERT INTO `producteurs` VALUES ('104', 'SCEA de Villardeau', 'Lieu Dit Villardeau, 18340 Senneçay', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Légume', '', null, '0', '46.9413', '2.4276');
INSERT INTO `producteurs` VALUES ('105', 'SCEA de la Croix de Guignas', '21 Chemin de Paris, 41500 Seris', null, null, '', null, '0', '47.7625', '1.50292');
INSERT INTO `producteurs` VALUES ('106', 'SCEA la Croix des Vignes', '27 Rue de Beaugency, 41290 Oucques La Nouvelle', null, null, '', null, '0', '47.8229', '1.29961');
INSERT INTO `producteurs` VALUES ('107', 'Saint Cyr Bio Val', '257 Rue des Serres, 45590 Saint-Cyr-en-Val', null, null, '', null, '0', '47.8534', '1.95904');
INSERT INTO `producteurs` VALUES ('108', 'Ternao', '5 rue Pierre et Marie Curie INGRE, 45140 Saint Jean de la Ruelle', null, 'Agriculture biologique\r\nFamille : XXX\r\nProduits : Fruit, Légume', '', null, '0', '47.9011', '1.85227');
INSERT INTO `producteurs` VALUES ('109', 'Terra Cérès', '17 rue des Entrepreneurs, 41700 Le Controis en Sologne', null, 'Agriculture biologique\r\nCertificat : Bio\r\nFamille : TRANS\r\nSite internet : https://terraceres.bio/', '', null, '0', '47.4344', '1.44497');
INSERT INTO `producteurs` VALUES ('110', 'Terres Dormes', '11 Les Bordes, 41100 ROCE', null, null, '', null, '0', '47.8127', '1.16536');
INSERT INTO `producteurs` VALUES ('111', 'Terres d\'Excellences', '8 Rue de Mérangle, 28500 Germainville', 'Exploitation agricole de 263 hectares en polyculture élevage et labelisée en agriculture biologique, la Ferme de Germainville possède un troupeau de vaches Angus d\'un peu plus de 200 animaux élevés uniquement à l\'herbe.\r\n La ferme cultive sur l\'autre partie de ses terres des céréales, légumineuses et cultures fourragères.', 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Huile, Céréale, Viande bovine, Produit carné', '', null, '0', '48.7407', '1.48027');
INSERT INTO `producteurs` VALUES ('112', 'Thomas GANEM', 'Les Hézeaux, 45360 Saint-Firmin-sur-Loire', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Légume', '', null, '0', '47.598', '2.67702');
INSERT INTO `producteurs` VALUES ('113', 'Val Bio Centre', '27bis Rue des Ponts Chartrains, 41000 Blois', null, 'Agriculture biologique\r\nCertificat : Bio\r\nProduits : Boisson non alcoolisée, Huile, Céréale, Oeuf, Fruit, Confiture, Aromate, Légume, Boisson', '', null, '0', '47.584', '1.34278');
